version: '3.9'
services:
  connect:
    restart: always
    image: connect-http:latest
    network_mode: host
    environment:
      - CO_ENV=local
      - CO_TWITTER_CONSUMER_TOKEN_KEY=my_consumer_key
      - CO_TWITTER_CONSUMER_TOKEN_SECRET=y_consumer_secret
      - CO_TWITTER_ACCESS_TOKEN_KEY=my_access_key
      - CO_TWITTER_ACCESS_TOKEN_SECRET=my_access_secret
      - CO_GITHUB_TOKEN=github_token